### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by Bullrich** [starikcetin/Extenject#6]
Can you please update the version in the `package.json` and tag a new release? I'm still using this version and there are problems that have been fixed in the commits, but a new release hasn't been released yet

**Comment by starikcetin** [comment]
It would be a real problem if we released a tag that doesn't exist on the main repo and they do release a version using that tag, then we would need to unpublish it from the OpenUPM, which the maintainer is not very keen on. 

I'll do something like `9.1.0-f1` and see if I can get it to work.

**Comment by starikcetin** [comment]
@Bullrich Try out `9.2.0-stcf3`.
